"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.defaultFromJSONParser = exports.InputFragment = exports.Fragment = exports.BlockFragment = void 0;
var Block_1 = require("./types/Block");
Object.defineProperty(exports, "BlockFragment", { enumerable: true, get: function () { return Block_1.Block; } });
var Fragment_1 = require("./types/Fragment");
Object.defineProperty(exports, "Fragment", { enumerable: true, get: function () { return Fragment_1.Fragment; } });
var Input_1 = require("./types/Input");
Object.defineProperty(exports, "InputFragment", { enumerable: true, get: function () { return Input_1.Input; } });
var FromJSONParser_1 = require("./types/FromJSONParser");
Object.defineProperty(exports, "defaultFromJSONParser", { enumerable: true, get: function () { return FromJSONParser_1.defaultFromJSONParser; } });
